.\" Manual para la práctica 4. Convertidor de Expresiones Regulares a AFD.
.\" Contacto con : norman_escom_ipn@yahoo.com.mx

.TH man 7 "12 May 2014" "0.0.1" "Manual de er2afd"
.SH NAME
er2afd \- convierte una expresión regular en un autómata finito determinista.
.SH SYNOPSIS
er2afd [Expresión Regular ] [-o AFD]
.SH DESCRIPTION
er2afd es un programa que recibe una expresión regular y entrega como 
resultado un autómata finito determinista.
.SH OPTIONS
Las opciones que puede recibir es el nombre del archivo que contendrá el A.F.D.
.SH SEE ALSO
er2afn(7), afn2afd(7),afd2min(7)
.SH BUGS
No se conocen "bugs".
.SH AUTHOR
Rafael Norman Saucedo Delgado (norman_escom_ipn@yahoo.com.mx)
Apunten sus nombre aquí.....
